"""Sandbox & security-grading package.

Public surface for the sandbox subsystem. Importing this package is safe at
startup: no subprocesses are spawned, no filesystem probing beyond an
in-memory import of the backend modules.
"""

from __future__ import annotations

from opensquilla.sandbox.backend import (
    Backend,
    BubblewrapBackend,
    NoopBackend,
    SeatbeltBackend,
    select_backend,
)
from opensquilla.sandbox.config import EffectiveMode, SandboxSettings
from opensquilla.sandbox.governance import (
    ApprovalGate,
    DenialLedger,
    action_fingerprint,
    gate_execution,
    on_successful_exec,
    post_denial_guard,
)
from opensquilla.sandbox.integration import (
    SandboxRuntime,
    configure_runtime,
    gate_action,
    get_runtime,
    record_success,
    reset_runtime,
    run_under_backend,
    sandboxed,
)
from opensquilla.sandbox.operation_runtime import (
    ArtifactOperationRequest,
    CustomOperationRequest,
    FilesystemOperationRequest,
    MediaOperationRequest,
    NetworkOperationRequest,
    OperationApproval,
    OperationPermissions,
    ProcessOperationRequest,
    SandboxOperation,
    SandboxOperationDomain,
    SandboxOperationRequest,
    SandboxOperationResult,
    SandboxOperationRuntime,
    SandboxToolDescriptor,
    SandboxToolGuard,
    prepare_tool_operation_guard,
    record_tool_operation_success,
    run_tool_handler_with_operation_guard,
)
from opensquilla.sandbox.policy import LevelHints, build_policy, select_level
from opensquilla.sandbox.stale_output_cache import (
    StaleOutputCache,
    get_stale_output_cache,
    reset_stale_output_cache,
)
from opensquilla.sandbox.types import (
    ALLOW,
    ApprovalDecision,
    DenialReason,
    DenialResult,
    FollowupTag,
    MountMode,
    MountSpec,
    NetworkMode,
    NetworkProxySpec,
    ResourceLimits,
    SandboxBackendError,
    SandboxPolicy,
    SandboxRequest,
    SandboxResult,
    SecurityLevel,
    SuggestedNextStep,
)

__all__ = [
    "ALLOW",
    "ApprovalDecision",
    "ApprovalGate",
    "ArtifactOperationRequest",
    "Backend",
    "BubblewrapBackend",
    "CustomOperationRequest",
    "DenialLedger",
    "DenialReason",
    "DenialResult",
    "EffectiveMode",
    "FilesystemOperationRequest",
    "FollowupTag",
    "LevelHints",
    "MediaOperationRequest",
    "MountMode",
    "MountSpec",
    "NetworkOperationRequest",
    "NetworkMode",
    "NetworkProxySpec",
    "NoopBackend",
    "OperationApproval",
    "OperationPermissions",
    "ProcessOperationRequest",
    "ResourceLimits",
    "SandboxBackendError",
    "SandboxPolicy",
    "SandboxRequest",
    "SandboxResult",
    "SandboxRuntime",
    "SandboxSettings",
    "SandboxOperation",
    "SandboxOperationDomain",
    "SandboxOperationRequest",
    "SandboxOperationResult",
    "SandboxOperationRuntime",
    "SandboxToolDescriptor",
    "SandboxToolGuard",
    "SeatbeltBackend",
    "SecurityLevel",
    "StaleOutputCache",
    "SuggestedNextStep",
    "action_fingerprint",
    "build_policy",
    "configure_runtime",
    "gate_action",
    "gate_execution",
    "get_runtime",
    "get_stale_output_cache",
    "on_successful_exec",
    "post_denial_guard",
    "prepare_tool_operation_guard",
    "record_success",
    "record_tool_operation_success",
    "reset_runtime",
    "reset_stale_output_cache",
    "run_under_backend",
    "run_tool_handler_with_operation_guard",
    "sandboxed",
    "select_backend",
    "select_level",
]
