"""Trusted, user-local managed toolchains for bundled skills."""

from opensquilla.skills.toolchains.manager import (
    ActivationReceipt,
    CapabilityReport,
    DownloadVerificationError,
    ManagedArtifactInstallLock,
    ToolchainError,
    ToolchainProbeError,
    UnsafeArchiveError,
    UnsupportedToolchainError,
    extract_managed_archive,
    install_component,
    invalidate_probe_cache,
    managed_toolchain_state_scope,
    probe_component,
    rollback_component,
)
from opensquilla.skills.toolchains.registry import (
    AuxiliaryAssetDescriptor,
    ToolchainDescriptor,
    UnknownComponentError,
    component_ids,
    describe_component,
    normalize_arch,
    normalize_platform,
    platform_key,
    trusted_brew_executable,
)
from opensquilla.skills.toolchains.runtime import (
    MEDIA_FONTS_ENV,
    PAPER_FONTS_ENV,
    ActiveComponentStatus,
    list_active_components,
    managed_env,
    resolve_managed_binary,
    resolve_managed_binary_passive,
    resolve_managed_resource,
)

__all__ = [
    "ActivationReceipt",
    "ActiveComponentStatus",
    "AuxiliaryAssetDescriptor",
    "CapabilityReport",
    "DownloadVerificationError",
    "ManagedArtifactInstallLock",
    "MEDIA_FONTS_ENV",
    "PAPER_FONTS_ENV",
    "ToolchainDescriptor",
    "ToolchainError",
    "ToolchainProbeError",
    "UnknownComponentError",
    "UnsafeArchiveError",
    "UnsupportedToolchainError",
    "component_ids",
    "describe_component",
    "extract_managed_archive",
    "install_component",
    "invalidate_probe_cache",
    "list_active_components",
    "managed_env",
    "managed_toolchain_state_scope",
    "normalize_arch",
    "normalize_platform",
    "platform_key",
    "probe_component",
    "resolve_managed_binary",
    "resolve_managed_binary_passive",
    "resolve_managed_resource",
    "rollback_component",
    "trusted_brew_executable",
]
