"""TurnRunner phase-class package (Phase C).

Public surface exports the InputStage trio (PR-C-1), the
ProviderAndToolsStage trio (PR-C-2), the PromptAssemblerStage septet
(PR-C-3), the AgentBootstrapStage sextet (PR-C-4), the
CompactionAndHistoryStage quartet (PR-C-5), the AttachmentStage trio
(PR-C-6), the StreamConsumerStage seven-port set (PR-C-7), and the
TurnFinalizerStage four-port set (PR-C-8). PR-C-9 adds
TurnTrailerStage.
"""

from __future__ import annotations

from opensquilla.engine.turn_runner.agent_bootstrap_stage import (
    AgentBootstrapStage,
    AgentBootstrapStageInput,
    AgentBootstrapStageOutput,
    AgentConfigBuilderPort,
    AgentFactoryPort,
    MemorySnapshotPort,
    ModelCatalogPort,
    SummarizerProviderPort,
    TimeoutBudgetPort,
    _AgentConfigAuxiliaries,
    _MemorySnapshotResult,
    _ResolvedBudgets,
    _ResolvedCatalog,
)
from opensquilla.engine.turn_runner.attachment_stage import (
    AttachmentMessageBuilderPort,
    AttachmentStage,
    AttachmentStageInput,
    AttachmentStageOutput,
)
from opensquilla.engine.turn_runner.compaction_and_history_stage import (
    CompactionAndHistoryStage,
    CompactionAndHistoryStageInput,
    CompactionAndHistoryStageOutput,
    HistoryLoaderPort,
    PreflightCompactionPort,
    RequestContextPrependPort,
    T3UpgradeCompactionPort,
)
from opensquilla.engine.turn_runner.context import TurnContext
from opensquilla.engine.turn_runner.harness import (
    _PromptReportBuilderAdapter,
    _RequestContextPrependAdapter,
    _TurnRunnerAgentConfigBuilderAdapter,
    _TurnRunnerAgentFactoryAdapter,
    _TurnRunnerAgentRunAdapter,
    _TurnRunnerAttachmentMessageBuilderAdapter,
    _TurnRunnerCompactionPersistAdapter,
    _TurnRunnerExtraContextAdapter,
    _TurnRunnerHistoryLoaderAdapter,
    _TurnRunnerMemoryFingerprintAdapter,
    _TurnRunnerMemorySnapshotAdapter,
    _TurnRunnerMemorySnapshotRefreshAdapter,
    _TurnRunnerMemorySyncNotifyAdapter,
    _TurnRunnerModelCatalogAdapter,
    _TurnRunnerPipelineExecutionAdapter,
    _TurnRunnerPreflightCompactionAdapter,
    _TurnRunnerPromptAssemblerAdapter,
    _TurnRunnerPromptConfigResolverAdapter,
    _TurnRunnerProviderResolverAdapter,
    _TurnRunnerRouterContextAdapter,
    _TurnRunnerSessionIdResolverAdapter,
    _TurnRunnerSessionTotalsAdapter,
    _TurnRunnerSummarizerProviderAdapter,
    _TurnRunnerSystemPromptRefreshAdapter,
    _TurnRunnerT3UpgradeCompactionAdapter,
    _TurnRunnerTimeoutBudgetAdapter,
    _TurnRunnerToolBuilderAdapter,
    _TurnRunnerTranscriptAppendAdapter,
    _TurnRunnerTurnErrorPersistAdapter,
    _TurnRunnerTurnMemoryCaptureAdapter,
)
from opensquilla.engine.turn_runner.input_stage import (
    ExtraContextResolver,
    InputStage,
    InputStageInput,
    InputStageOutput,
    SessionAppendPort,
)
from opensquilla.engine.turn_runner.outcome import StageOutcome
from opensquilla.engine.turn_runner.prompt_assembler_stage import (
    MemoryFingerprintPort,
    PipelineExecutionPort,
    PromptAssemblerPort,
    PromptAssemblerStage,
    PromptAssemblerStageInput,
    PromptAssemblerStageOutput,
    PromptConfigResolverPort,
    PromptReportBuilderPort,
    RouterContextPort,
    RunPipelineRequest,
    SessionIdResolverPort,
)
from opensquilla.engine.turn_runner.provider_and_tools_stage import (
    ProviderAndToolsStage,
    ProviderAndToolsStageInput,
    ProviderAndToolsStageOutput,
    ProviderResolverPort,
    ToolBuilderPort,
)
from opensquilla.engine.turn_runner.stream_consumer_stage import (
    AgentRunPort,
    CompactionPersistPort,
    MemorySnapshotRefreshPort,
    MemorySyncNotifyPort,
    StreamConsumerStage,
    StreamConsumerStageInput,
    SystemPromptRefreshPort,
    WarningTransformer,
    _StreamState,
)
from opensquilla.engine.turn_runner.turn_finalizer_stage import (
    CostRollupResult,
    SessionTotalsPort,
    TranscriptAppendPort,
    TurnErrorPersistPort,
    TurnFinalizerStage,
    TurnFinalizerStageInput,
    TurnFinalizerStageOutput,
    TurnMemoryCapturePort,
)

__all__ = [
    "AgentBootstrapStage",
    "AgentBootstrapStageInput",
    "AgentBootstrapStageOutput",
    "AgentConfigBuilderPort",
    "AgentFactoryPort",
    "AgentRunPort",
    "AttachmentMessageBuilderPort",
    "AttachmentStage",
    "AttachmentStageInput",
    "AttachmentStageOutput",
    "CompactionAndHistoryStage",
    "CompactionAndHistoryStageInput",
    "CompactionAndHistoryStageOutput",
    "CompactionPersistPort",
    "CostRollupResult",
    "ExtraContextResolver",
    "HistoryLoaderPort",
    "InputStage",
    "InputStageInput",
    "InputStageOutput",
    "MemoryFingerprintPort",
    "MemorySnapshotPort",
    "MemorySnapshotRefreshPort",
    "MemorySyncNotifyPort",
    "ModelCatalogPort",
    "PipelineExecutionPort",
    "PreflightCompactionPort",
    "PromptAssemblerPort",
    "PromptAssemblerStage",
    "PromptAssemblerStageInput",
    "PromptAssemblerStageOutput",
    "PromptConfigResolverPort",
    "PromptReportBuilderPort",
    "ProviderAndToolsStage",
    "ProviderAndToolsStageInput",
    "ProviderAndToolsStageOutput",
    "ProviderResolverPort",
    "RequestContextPrependPort",
    "RouterContextPort",
    "RunPipelineRequest",
    "SessionAppendPort",
    "SessionIdResolverPort",
    "SessionTotalsPort",
    "StageOutcome",
    "StreamConsumerStage",
    "StreamConsumerStageInput",
    "SummarizerProviderPort",
    "SystemPromptRefreshPort",
    "T3UpgradeCompactionPort",
    "TimeoutBudgetPort",
    "ToolBuilderPort",
    "TranscriptAppendPort",
    "TurnContext",
    "TurnErrorPersistPort",
    "TurnFinalizerStage",
    "TurnFinalizerStageInput",
    "TurnFinalizerStageOutput",
    "TurnMemoryCapturePort",
    "WarningTransformer",
    "_AgentConfigAuxiliaries",
    "_MemorySnapshotResult",
    "_PromptReportBuilderAdapter",
    "_RequestContextPrependAdapter",
    "_ResolvedBudgets",
    "_ResolvedCatalog",
    "_StreamState",
    "_TurnRunnerAgentConfigBuilderAdapter",
    "_TurnRunnerAgentFactoryAdapter",
    "_TurnRunnerAgentRunAdapter",
    "_TurnRunnerAttachmentMessageBuilderAdapter",
    "_TurnRunnerCompactionPersistAdapter",
    "_TurnRunnerExtraContextAdapter",
    "_TurnRunnerHistoryLoaderAdapter",
    "_TurnRunnerMemoryFingerprintAdapter",
    "_TurnRunnerMemorySnapshotAdapter",
    "_TurnRunnerMemorySnapshotRefreshAdapter",
    "_TurnRunnerMemorySyncNotifyAdapter",
    "_TurnRunnerModelCatalogAdapter",
    "_TurnRunnerPipelineExecutionAdapter",
    "_TurnRunnerPreflightCompactionAdapter",
    "_TurnRunnerPromptAssemblerAdapter",
    "_TurnRunnerPromptConfigResolverAdapter",
    "_TurnRunnerProviderResolverAdapter",
    "_TurnRunnerRouterContextAdapter",
    "_TurnRunnerSessionIdResolverAdapter",
    "_TurnRunnerSessionTotalsAdapter",
    "_TurnRunnerSummarizerProviderAdapter",
    "_TurnRunnerSystemPromptRefreshAdapter",
    "_TurnRunnerT3UpgradeCompactionAdapter",
    "_TurnRunnerTimeoutBudgetAdapter",
    "_TurnRunnerToolBuilderAdapter",
    "_TurnRunnerTranscriptAppendAdapter",
    "_TurnRunnerTurnErrorPersistAdapter",
    "_TurnRunnerTurnMemoryCaptureAdapter",
]
