<template>
  <details v-if="proposals.length" ref="rootRef" class="sk-group sk-group--proposals" open>
    <summary class="sk-group__head">
      <span class="sk-group__caret">▾</span>
      <span class="sk-group__label">Pending Proposals</span>
      <span class="sk-group__count">{{ proposals.length }}</span>
      <span class="sk-group__meta">meta-skill-creator candidates awaiting your accept/reject decision.</span>
    </summary>
    <div class="sk-proposals-list">
      <div v-for="p in proposals" :key="p.proposal_id" class="sk-proposal-row">
        <div class="sk-proposal-row__head">
          <code class="sk-proposal-row__id">{{ p.proposal_id }}</code>
          <span v-if="p.auto_enable_eligible" class="sk-prop-chip sk-prop-chip--ok">gates ok</span>
          <span v-else class="sk-prop-chip sk-prop-chip--warn">gates blocked</span>
          <span
            v-if="typeof p.triggered_by === 'string' && p.triggered_by.startsWith('auto_')"
            class="sk-prop-chip sk-prop-chip--auto"
            :title="`Auto-generated by ${p.triggered_by}`"
          >auto</span>
          <span v-if="p.auto_enable && p.auto_enable.status" class="sk-prop-chip sk-prop-chip--warn" :title="p.auto_enable.reason || ''">auto-enable: {{ p.auto_enable.status }}</span>
          <span v-if="p.auto_enable && p.auto_enable.validation_profile" class="sk-prop-chip" title="validation profile">{{ p.auto_enable.validation_profile }}</span>
          <span v-if="p.chain_hash" class="sk-prop-hash" title="chain hash">{{ String(p.chain_hash).slice(0, 8) }}</span>
        </div>
        <div class="sk-proposal-row__actions">
          <button class="btn btn--ghost btn--sm" type="button" @click="emit('show', p.proposal_id)">Show</button>
          <button class="btn btn--primary btn--sm" type="button" @click="emit('accept', p.proposal_id)">Accept</button>
          <button class="btn btn--ghost btn--sm" type="button" @click="emit('reject', p.proposal_id)">Reject</button>
        </div>
      </div>
    </div>
  </details>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import type { Proposal } from '@/types/skills'

defineProps<{
  proposals: Proposal[]
}>()

const emit = defineEmits<{
  show: [proposalId: string]
  accept: [proposalId: string]
  reject: [proposalId: string]
}>()

const rootRef = ref<HTMLElement | null>(null)

defineExpose({
  scrollIntoView(options?: ScrollIntoViewOptions) {
    rootRef.value?.scrollIntoView(options)
  },
})
</script>
