#!/usr/bin/env python3
"""Generate the WebUI router-tier/SelectionMode contract from Python data."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
OUTPUT = ROOT / "opensquilla-webui/src/types/generated/router_tier_contract.ts"
sys.path.insert(0, str(SRC))

from opensquilla.router_tiers import (  # noqa: E402
    CUSTOM_B5_MAX_PROPOSERS,
    CUSTOM_B5_MAX_TOTAL_CALLS,
    CUSTOM_B5_MIN_PROPOSERS,
    CUSTOM_B5_RECOMMENDED_MAX,
    CUSTOM_B5_RECOMMENDED_MIN,
    CUSTOM_B5_SELECTION_MODE,
    DEFAULT_ENSEMBLE_SELECTION_MODE,
    DEFAULT_TEXT_TIER,
    DORMANT_SHARED_SELECTION_MODES,
    ENSEMBLE_CANDIDATE_ROLES,
    ENSEMBLE_SELECTION_MODE_ORDER,
    IMAGE_TIER,
    LEGACY_OPENROUTER_MODEL_OPTIONS,
    LEGACY_TEXT_TIER_ALIASES,
    PROVIDER_RECOMMENDED_ENSEMBLE_SELECTION_MODES,
    ROUTER_DYNAMIC_SELECTION_MODE,
    ROUTER_TIER_ENSEMBLE_SELECTION_MODES,
    SELECTION_FINGERPRINT_FIELDS,
    SELECTION_MODE_OWNERSHIP_ROLES,
    STATIC_B5_PROFILES,
    STATIC_B5_SELECTION_MODE_PROVIDERS,
    STATIC_OPENROUTER_B5_SELECTION_MODE,
    STATIC_TOKENRHYTHM_B5_SELECTION_MODE,
    TEXT_TIERS,
    TIER_PROVIDER_ROLES,
)

GENERATED_HEADER = "// @generated by scripts/generate_router_tier_contract.py; do not edit."


def _json(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(", ", ": "))


def _profile_block() -> str:
    rows: list[str] = []
    for mode in ENSEMBLE_SELECTION_MODE_ORDER:
        profile = STATIC_B5_PROFILES.get(mode)
        if profile is None:
            continue
        rows.append(
            "  "
            + json.dumps(mode)
            + ": {\n"
            + f"    provider: {_json(profile.provider_id)},\n"
            + f"    label: {_json(profile.label)},\n"
            + f"    proposers: {_json(list(profile.proposer_models))} as const,\n"
            + f"    aggregator: {_json(profile.aggregator_model)},\n"
            + f"    apiKeyEnv: {_json(profile.api_key_env)},\n"
            + f"    ownershipRole: {_json(profile.ownership_role)},\n"
            + "  },"
        )
    return "\n".join(rows)


def render() -> str:
    selection_modes = [
        mode
        for mode in ENSEMBLE_SELECTION_MODE_ORDER
        if mode in ROUTER_TIER_ENSEMBLE_SELECTION_MODES
    ]
    independent_modes = [
        mode for mode in DORMANT_SHARED_SELECTION_MODES if mode in selection_modes
    ]
    legacy_aliases = _json(LEGACY_TEXT_TIER_ALIASES)
    static_provider_map = _json(STATIC_B5_SELECTION_MODE_PROVIDERS)
    provider_recommendations = _json(PROVIDER_RECOMMENDED_ENSEMBLE_SELECTION_MODES)
    ownership_roles = _json(SELECTION_MODE_OWNERSHIP_ROLES)
    legacy_model_options = _json(list(LEGACY_OPENROUTER_MODEL_OPTIONS))
    return f"""{GENERATED_HEADER}

export const TEXT_TIERS = {_json(list(TEXT_TIERS))} as const
export const DEFAULT_TEXT_TIER = {_json(DEFAULT_TEXT_TIER)}
export const IMAGE_TIER = {_json(IMAGE_TIER)}
export const LEGACY_TEXT_TIER_ALIASES:
  Readonly<Record<string, string>> = {legacy_aliases}

export const STATIC_OPENROUTER_B5_SELECTION_MODE = {_json(STATIC_OPENROUTER_B5_SELECTION_MODE)}
export const STATIC_TOKENRHYTHM_B5_SELECTION_MODE = {_json(STATIC_TOKENRHYTHM_B5_SELECTION_MODE)}
export const CUSTOM_B5_SELECTION_MODE = {_json(CUSTOM_B5_SELECTION_MODE)}
export const ROUTER_DYNAMIC_SELECTION_MODE = {_json(ROUTER_DYNAMIC_SELECTION_MODE)}
export const DEFAULT_ENSEMBLE_SELECTION_MODE = {_json(DEFAULT_ENSEMBLE_SELECTION_MODE)}

export const ENSEMBLE_SELECTION_MODES = {_json(selection_modes)} as const
export const INDEPENDENT_ENSEMBLE_SELECTION_MODES = {_json(independent_modes)} as const
export const DORMANT_SHARED_SELECTION_MODES = {_json(independent_modes)} as const
export const TIER_PROVIDER_ROLES = {_json(list(TIER_PROVIDER_ROLES))} as const
export const SELECTION_FINGERPRINT_FIELDS = {_json(list(SELECTION_FINGERPRINT_FIELDS))} as const
export type SelectionMode = typeof ENSEMBLE_SELECTION_MODES[number]
export type EnsembleSelectionMode = SelectionMode

export interface StaticB5Profile {{
  provider: string
  label: string
  proposers: readonly string[]
  aggregator: string
  apiKeyEnv: string
  ownershipRole: string
}}

export const STATIC_B5_PROFILES: Record<string, StaticB5Profile> = {{
{_profile_block()}
}}

export const STATIC_B5_SELECTION_MODE_PROVIDERS:
  Readonly<Record<string, string>> = {static_provider_map}
export const PROVIDER_RECOMMENDED_ENSEMBLE_SELECTION_MODES:
  Readonly<Record<string, string>> = {provider_recommendations}
export const SELECTION_MODE_OWNERSHIP_ROLES:
  Readonly<Record<string, string>> = {ownership_roles}

export const ENSEMBLE_CANDIDATE_ROLES = {_json(list(ENSEMBLE_CANDIDATE_ROLES))} as const
export const CUSTOM_B5_MIN_PROPOSERS = {CUSTOM_B5_MIN_PROPOSERS}
export const CUSTOM_B5_MAX_PROPOSERS = {CUSTOM_B5_MAX_PROPOSERS}
export const CUSTOM_B5_MAX_TOTAL_CALLS = {CUSTOM_B5_MAX_TOTAL_CALLS}
export const CUSTOM_B5_RECOMMENDED_MIN = {CUSTOM_B5_RECOMMENDED_MIN}
export const CUSTOM_B5_RECOMMENDED_MAX = {CUSTOM_B5_RECOMMENDED_MAX}

export const OPENROUTER_FIXED_ENSEMBLE_PROPOSERS =
  STATIC_B5_PROFILES[STATIC_OPENROUTER_B5_SELECTION_MODE].proposers
export const OPENROUTER_FIXED_ENSEMBLE_AGGREGATOR =
  STATIC_B5_PROFILES[STATIC_OPENROUTER_B5_SELECTION_MODE].aggregator
export const TOKENRHYTHM_FIXED_ENSEMBLE_PROPOSERS =
  STATIC_B5_PROFILES[STATIC_TOKENRHYTHM_B5_SELECTION_MODE].proposers
export const TOKENRHYTHM_FIXED_ENSEMBLE_AGGREGATOR =
  STATIC_B5_PROFILES[STATIC_TOKENRHYTHM_B5_SELECTION_MODE].aggregator
export const LEGACY_OPENROUTER_MODEL_OPTIONS = {legacy_model_options} as const

export function staticB5ModeForProvider(provider: unknown): string | null {{
  const id = String(provider || '').trim().toLowerCase()
  if (!id) return null
  for (const [mode, profile] of Object.entries(STATIC_B5_PROFILES)) {{
    if (profile.provider === id) return mode
  }}
  return null
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true", help="fail if the checked-in file is stale")
    group.add_argument("--write", action="store_true", help="write the generated contract")
    args = parser.parse_args()
    rendered = render()
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
    if args.check:
        if current != rendered:
            print(f"stale generated contract: {OUTPUT}", file=sys.stderr)
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
