/**
 * Version 4 adds the candidate-preview lifecycle on the Desktop side and
 * enables the already-typed browser inspection methods for the active HTML
 * surface and browser actions only for an offline candidate preview. Version 3
 * remains accepted on the wire so an older Gateway can be upgraded
 * independently of the Electron shell.
 */
export const DESKTOP_ARTIFACT_BRIDGE_PROTOCOL_VERSION = 5 as const
export const DESKTOP_ARTIFACT_BRIDGE_PROTOCOL_VERSION_V4 = 4 as const
export const DESKTOP_ARTIFACT_BRIDGE_PROTOCOL_VERSION_V3 = 3 as const
export const DESKTOP_ARTIFACT_BRIDGE_PROTOCOL_VERSIONS = [
  DESKTOP_ARTIFACT_BRIDGE_PROTOCOL_VERSION_V3,
  DESKTOP_ARTIFACT_BRIDGE_PROTOCOL_VERSION_V4,
  DESKTOP_ARTIFACT_BRIDGE_PROTOCOL_VERSION,
] as const
export type DesktopArtifactBridgeProtocolVersion =
  typeof DESKTOP_ARTIFACT_BRIDGE_PROTOCOL_VERSION_V3
  | typeof DESKTOP_ARTIFACT_BRIDGE_PROTOCOL_VERSION_V4
  | typeof DESKTOP_ARTIFACT_BRIDGE_PROTOCOL_VERSION

export const DESKTOP_ARTIFACT_BRIDGE_METHODS = [
  'captureSelection',
  'resolveAnnotationSelection',
  'focusAnnotation',
  'browserInspect',
  'browserAct',
  'screenshot',
  'officeFlush',
  'reloadSurface',
  'bindCandidatePreview',
  'restoreCanonicalPreview',
] as const

export type DesktopArtifactBridgeMethod =
  typeof DESKTOP_ARTIFACT_BRIDGE_METHODS[number]

export interface DesktopArtifactBridgeCapabilities {
  /** Negotiated protocol of the currently active surface (v3 or v4). */
  version: DesktopArtifactBridgeProtocolVersion
  available: boolean
  captureSelection: boolean
  resolveAnnotationSelection: boolean
  focusAnnotation: boolean
  browserInspect: boolean
  /** True only while a v4 offline candidate preview is bound to the surface. */
  browserAct: boolean
  screenshot: boolean
  officeFlush: boolean
  reloadSurface: boolean
  /** v4 candidate preview lifecycle; false when the Gateway cannot bind safely. */
  bindCandidatePreview: boolean
  restoreCanonicalPreview: boolean
}

/**
 * Protocol metadata advertised by Desktop independently of the currently
 * active surface. Actual method availability is queried at call time and is
 * false unless a protocol-v4 active surface has an implementation. Protocol
 * v3 callers remain accepted during the rolling Desktop/Gateway upgrade.
 */
export const DESKTOP_ARTIFACT_BRIDGE_CONTRACT = {
  version: DESKTOP_ARTIFACT_BRIDGE_PROTOCOL_VERSION,
  surfaceBinding: 'turn' as const,
  methods: DESKTOP_ARTIFACT_BRIDGE_METHODS,
  acceptsSurfaceId: false as const,
  acceptsUrl: false as const,
  acceptsJavascriptExpression: false as const,
  acceptsRawCdp: false as const,
}

export const DESKTOP_ARTIFACT_BRIDGE_UNSUPPORTED_CAPABILITIES:
DesktopArtifactBridgeCapabilities = Object.freeze({
  version: DESKTOP_ARTIFACT_BRIDGE_PROTOCOL_VERSION,
  available: false,
  captureSelection: false,
  resolveAnnotationSelection: false,
  focusAnnotation: false,
  browserInspect: false,
  browserAct: false,
  screenshot: false,
  officeFlush: false,
  reloadSurface: false,
  bindCandidatePreview: false,
  restoreCanonicalPreview: false,
})

interface DesktopArtifactBridgeRequestBase {
  version: DesktopArtifactBridgeProtocolVersion
}

export type DesktopArtifactCaptureSelectionRequest = DesktopArtifactBridgeRequestBase

export interface DesktopArtifactResolveAnnotationSelectionRequest
  extends DesktopArtifactBridgeRequestBase {
  activePreviewArtifactId: string
  selectionId: string
  tagName: string
  elementPath: string
  domSha256?: string
  elementProofSha256: string
}

export interface DesktopArtifactFocusAnnotationRequest
  extends DesktopArtifactBridgeRequestBase {
  activePreviewArtifactId: string
  annotationId: string
  scopeId: string
  tagName: string
  elementPath: string
  elementProofSha256: string
}

export type DesktopArtifactBrowserInspectScope =
  | 'document'
  | 'selection'
  | 'viewport'

export interface DesktopArtifactBrowserInspectRequest
  extends DesktopArtifactBridgeRequestBase {
  scope: DesktopArtifactBrowserInspectScope
  maxNodes: number
  /** Internal identity probe; must not replace the active anchor table. */
  identityOnly?: boolean
  /** Required while a v4 candidate preview is active; omitted for canonical/v3 calls. */
  candidateHandle?: string
}

/**
 * Candidate handles are generated by the Gateway and are intentionally opaque
 * to Desktop.  They never carry an artifact id, path, URL, or source bytes.
 */
export interface DesktopArtifactBindCandidatePreviewRequest
  extends DesktopArtifactBridgeRequestBase {
  candidateHandle: string
}

export interface DesktopArtifactRestoreCanonicalPreviewRequest
  extends DesktopArtifactBridgeRequestBase {
  /** The opaque candidate currently owned by the caller being restored. */
  candidateHandle: string
}

export const DESKTOP_ARTIFACT_BROWSER_ACTIONS = [
  'click',
  'focus',
  'type',
  'press',
  'scroll',
] as const

export type DesktopArtifactBrowserAction =
  typeof DESKTOP_ARTIFACT_BROWSER_ACTIONS[number]

export const DESKTOP_ARTIFACT_BROWSER_KEYS = [
  'Enter',
  'Tab',
  'Escape',
  'Backspace',
  'Delete',
  'Space',
  'ArrowUp',
  'ArrowDown',
  'ArrowLeft',
  'ArrowRight',
  'Home',
  'End',
  'PageUp',
  'PageDown',
] as const

export type DesktopArtifactBrowserKey =
  typeof DESKTOP_ARTIFACT_BROWSER_KEYS[number]

export interface DesktopArtifactBrowserClickRequest
  extends DesktopArtifactBridgeRequestBase {
  action: 'click' | 'focus'
  anchor: string
  /** Required by native v4 candidate actions; omitted for legacy/canonical calls. */
  candidateHandle?: string
}

export interface DesktopArtifactBrowserTypeRequest
  extends DesktopArtifactBridgeRequestBase {
  action: 'type'
  anchor: string
  text: string
  replace: boolean
  /** Required by native v4 candidate actions; omitted for legacy/canonical calls. */
  candidateHandle?: string
}

export interface DesktopArtifactBrowserPressRequest
  extends DesktopArtifactBridgeRequestBase {
  action: 'press'
  key: DesktopArtifactBrowserKey
  /** Required by native v4 candidate actions; omitted for legacy/canonical calls. */
  candidateHandle?: string
}

export interface DesktopArtifactBrowserScrollRequest
  extends DesktopArtifactBridgeRequestBase {
  action: 'scroll'
  direction: 'up' | 'down' | 'left' | 'right'
  amount: 'line' | 'page'
  /** Required by native v4 candidate actions; omitted for legacy/canonical calls. */
  candidateHandle?: string
}

export type DesktopArtifactBrowserActRequest =
  | DesktopArtifactBrowserClickRequest
  | DesktopArtifactBrowserTypeRequest
  | DesktopArtifactBrowserPressRequest
  | DesktopArtifactBrowserScrollRequest

export interface DesktopArtifactScreenshotRequest extends DesktopArtifactBridgeRequestBase {
  /** Required while a v4 candidate preview is active; omitted for canonical/v3 calls. */
  candidateHandle?: string
}
export type DesktopArtifactOfficeFlushRequest = DesktopArtifactBridgeRequestBase
export interface DesktopArtifactReloadSurfaceRequest extends DesktopArtifactBridgeRequestBase {
  /** Required while a v4 candidate preview is active; omitted for canonical/v3 calls. */
  candidateHandle?: string
}

export type DesktopArtifactSelectionKind =
  | 'none'
  | 'text'
  | 'cell'
  | 'range'
  | 'shape'
  | 'slide'
  | 'dom'

export interface DesktopArtifactSelectionSnapshot {
  kind: DesktopArtifactSelectionKind
  anchor?: string
  text?: string
  truncated?: boolean
}

export interface DesktopArtifactResolvedAnnotationSelection {
  activePreviewArtifactId: string
  selectionId: string
  tagName: string
  elementPath: string
  domSha256?: string
  elementProofSha256: string
  scopeId: string
  rect: {
    x: number
    y: number
    width: number
    height: number
  }
}

export interface DesktopArtifactBrowserNode {
  anchor: string
  role?: string
  name?: string
  text?: string
  interactive?: boolean
  disabled?: boolean
  selected?: boolean
}

export interface DesktopArtifactBrowserSnapshot {
  scope: DesktopArtifactBrowserInspectScope
  nodes: DesktopArtifactBrowserNode[]
  truncated: boolean
  /** v4 active-surface identity; omitted by legacy test doubles/clients. */
  activePreviewArtifactId?: string | null
  /** v4 binding scope; omitted by legacy test doubles/clients. */
  scopeId?: string
  /** Opaque candidate handle while a candidate preview is bound. */
  candidateHandle?: string | null
  /** v5 process-local binding generation; never projected to the model. */
  bindingGeneration?: number
}

export interface DesktopArtifactBrowserActResult {
  performed: boolean
  changed: boolean
}

export interface DesktopArtifactBindCandidatePreviewResult {
  bound: true
  candidateHandle: string
}

export interface DesktopArtifactRestoreCanonicalPreviewResult {
  restored: true
}

export interface DesktopArtifactScreenshotResult {
  mime: 'image/png'
  data: Uint8Array
  width: number
  height: number
}

export interface DesktopArtifactOfficeFlushResult {
  flushed: boolean
  revision?: string
}

export interface DesktopArtifactReloadSurfaceResult {
  reloaded: true
}

export interface DesktopArtifactFocusAnnotationResult {
  focused: true
  activePreviewArtifactId: string
}

export interface DesktopArtifactBridgeRequestByMethod {
  captureSelection: DesktopArtifactCaptureSelectionRequest
  resolveAnnotationSelection: DesktopArtifactResolveAnnotationSelectionRequest
  focusAnnotation: DesktopArtifactFocusAnnotationRequest
  browserInspect: DesktopArtifactBrowserInspectRequest
  browserAct: DesktopArtifactBrowserActRequest
  screenshot: DesktopArtifactScreenshotRequest
  officeFlush: DesktopArtifactOfficeFlushRequest
  reloadSurface: DesktopArtifactReloadSurfaceRequest
  bindCandidatePreview: DesktopArtifactBindCandidatePreviewRequest
  restoreCanonicalPreview: DesktopArtifactRestoreCanonicalPreviewRequest
}

export interface DesktopArtifactBridgeValueByMethod {
  captureSelection: DesktopArtifactSelectionSnapshot
  resolveAnnotationSelection: DesktopArtifactResolvedAnnotationSelection
  focusAnnotation: DesktopArtifactFocusAnnotationResult
  browserInspect: DesktopArtifactBrowserSnapshot
  browserAct: DesktopArtifactBrowserActResult
  screenshot: DesktopArtifactScreenshotResult
  officeFlush: DesktopArtifactOfficeFlushResult
  reloadSurface: DesktopArtifactReloadSurfaceResult
  bindCandidatePreview: DesktopArtifactBindCandidatePreviewResult
  restoreCanonicalPreview: DesktopArtifactRestoreCanonicalPreviewResult
}

function objectRecord(value: unknown): Record<string, unknown> | null {
  return value && typeof value === 'object' && !Array.isArray(value)
    ? value as Record<string, unknown>
    : null
}

function parseRequest(
  value: unknown,
  allowedKeys: readonly string[],
  label: string,
): Record<string, unknown> {
  const request = objectRecord(value)
  if (
    !request
    || !DESKTOP_ARTIFACT_BRIDGE_PROTOCOL_VERSIONS.includes(
      request.version as DesktopArtifactBridgeProtocolVersion,
    )
    || Object.keys(request).some(key => !allowedKeys.includes(key))
  ) {
    throw new Error(`The Desktop artifact ${label} request is invalid.`)
  }
  return request
}

function parseVersionOnlyRequest(
  value: unknown,
  label: string,
): DesktopArtifactBridgeRequestBase {
  parseRequest(value, ['version'], label)
  return { version: requestVersion(value) }
}

function requestVersion(value: unknown): DesktopArtifactBridgeProtocolVersion {
  const request = objectRecord(value)
  if (!request || !DESKTOP_ARTIFACT_BRIDGE_PROTOCOL_VERSIONS.includes(
    request.version as DesktopArtifactBridgeProtocolVersion,
  )) throw new Error('The Desktop artifact bridge protocol version is invalid.')
  return request.version as DesktopArtifactBridgeProtocolVersion
}

function parseAnchor(value: unknown): string {
  if (typeof value !== 'string' || !/^[A-Za-z0-9_-]{1,128}$/.test(value)) {
    throw new Error('The Desktop artifact browser anchor is invalid.')
  }
  return value
}

function parseCandidateHandle(value: unknown): string {
  if (
    typeof value !== 'string'
    || !/^candidate_[A-Za-z0-9_-]{16,128}$/.test(value)
  ) {
    throw new Error('The Desktop artifact candidate handle is invalid.')
  }
  return value
}

function parseOptionalCandidateHandle(
  request: Record<string, unknown>,
): string | undefined {
  return request.candidateHandle === undefined
    ? undefined
    : parseCandidateHandle(request.candidateHandle)
}

function parseV4OnlyRequest(
  value: unknown,
  allowedKeys: readonly string[],
  label: string,
): Record<string, unknown> {
  const request = parseRequest(value, allowedKeys, label)
  if (requestVersion(value) < DESKTOP_ARTIFACT_BRIDGE_PROTOCOL_VERSION_V4) {
    throw new Error(`The Desktop artifact ${label} requires protocol-v4 or newer.`)
  }
  return request
}

function parseAnnotationElementPath(value: unknown): string {
  if (typeof value !== 'string' || value.length === 0 || value.length > 4096) {
    throw new Error('The Desktop artifact annotation element path is invalid.')
  }
  let parsed: unknown
  try {
    parsed = JSON.parse(value)
  } catch {
    throw new Error('The Desktop artifact annotation element path is invalid.')
  }
  if (
    !Array.isArray(parsed)
    || parsed.length < 1
    || parsed.length > 128
    || parsed.some(segment => (
      !Array.isArray(segment)
      || segment.length !== 3
      || typeof segment[0] !== 'string'
      || segment[0].length > 256
      || /[\u0000-\u001f\u007f]/.test(segment[0])
      || typeof segment[1] !== 'string'
      || !/^[a-z][a-z0-9._:-]{0,63}$/.test(segment[1])
      || !Number.isSafeInteger(segment[2])
      || segment[2] < 1
    ))
    || JSON.stringify(parsed) !== value
  ) {
    throw new Error('The Desktop artifact annotation element path is invalid.')
  }
  return value
}

function parseActivePreviewArtifactId(value: unknown): string {
  if (typeof value !== 'string' || !/^art-[A-Za-z0-9_-]{1,200}$/.test(value)) {
    throw new Error('The Desktop artifact preview identity is invalid.')
  }
  return value
}

export function parseDesktopArtifactCaptureSelectionRequest(
  value: unknown,
): DesktopArtifactCaptureSelectionRequest {
  return parseVersionOnlyRequest(value, 'selection capture')
}

export function parseDesktopArtifactResolveAnnotationSelectionRequest(
  value: unknown,
): DesktopArtifactResolveAnnotationSelectionRequest {
  const request = parseRequest(
    value,
    [
      'version',
      'activePreviewArtifactId',
      'selectionId',
      'tagName',
      'elementPath',
      'domSha256',
      'elementProofSha256',
    ],
    'annotation selection resolution',
  )
  if (
    typeof request.selectionId !== 'string'
    || !/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(request.selectionId)
    || typeof request.tagName !== 'string'
    || !/^[a-z][a-z0-9._:-]{0,63}$/.test(request.tagName)
    || (request.domSha256 !== undefined && (
      typeof request.domSha256 !== 'string'
      || !/^[a-f0-9]{64}$/.test(request.domSha256)
    ))
    || typeof request.elementProofSha256 !== 'string'
    || !/^[a-f0-9]{64}$/.test(request.elementProofSha256)
  ) {
    throw new Error('The Desktop artifact annotation selection is invalid.')
  }
  return {
    version: requestVersion(value),
    activePreviewArtifactId: parseActivePreviewArtifactId(
      request.activePreviewArtifactId,
    ),
    selectionId: request.selectionId,
    tagName: request.tagName,
    elementPath: parseAnnotationElementPath(request.elementPath),
    ...(request.domSha256 === undefined ? {} : { domSha256: request.domSha256 }),
    elementProofSha256: request.elementProofSha256,
  }
}

export function parseDesktopArtifactFocusAnnotationRequest(
  value: unknown,
): DesktopArtifactFocusAnnotationRequest {
  const request = parseRequest(
    value,
    [
      'version',
      'activePreviewArtifactId',
      'annotationId',
      'scopeId',
      'tagName',
      'elementPath',
      'elementProofSha256',
    ],
    'annotation focus',
  )
  if (
    typeof request.annotationId !== 'string'
    || !/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(request.annotationId)
    || typeof request.scopeId !== 'string'
    || request.scopeId.length === 0
    || request.scopeId.length > 512
    || /[\u0000-\u001f\u007f]/.test(request.scopeId)
    || typeof request.tagName !== 'string'
    || !/^[a-z][a-z0-9._:-]{0,63}$/.test(request.tagName)
    || typeof request.elementProofSha256 !== 'string'
    || !/^[a-f0-9]{64}$/.test(request.elementProofSha256)
  ) {
    throw new Error('The Desktop artifact annotation focus request is invalid.')
  }
  return {
    version: requestVersion(value),
    activePreviewArtifactId: parseActivePreviewArtifactId(
      request.activePreviewArtifactId,
    ),
    annotationId: request.annotationId,
    scopeId: request.scopeId,
    tagName: request.tagName,
    elementPath: parseAnnotationElementPath(request.elementPath),
    elementProofSha256: request.elementProofSha256,
  }
}

export function parseDesktopArtifactBrowserInspectRequest(
  value: unknown,
): DesktopArtifactBrowserInspectRequest {
  const request = parseRequest(
    value,
    ['version', 'scope', 'maxNodes', 'identityOnly', 'candidateHandle'],
    'browser inspection',
  )
  const scope = request.scope
  if (scope !== 'document' && scope !== 'selection' && scope !== 'viewport') {
    throw new Error('Choose a supported Desktop artifact inspection scope.')
  }
  const maxNodes = request.maxNodes
  if (!Number.isInteger(maxNodes) || (maxNodes as number) < 1 || (maxNodes as number) > 200) {
    throw new Error('The Desktop artifact browser inspection limit is invalid.')
  }
  if (request.identityOnly !== undefined && typeof request.identityOnly !== 'boolean') {
    throw new Error('The Desktop artifact browser identity probe is invalid.')
  }
  const candidateHandle = parseOptionalCandidateHandle(request)
  return {
    version: requestVersion(value),
    scope,
    maxNodes: maxNodes as number,
    ...(request.identityOnly === true ? { identityOnly: true } : {}),
    ...(candidateHandle === undefined ? {} : { candidateHandle }),
  }
}

export function parseDesktopArtifactBrowserActRequest(
  value: unknown,
): DesktopArtifactBrowserActRequest {
  const base = objectRecord(value)
  const action = base?.action
  if (!DESKTOP_ARTIFACT_BROWSER_ACTIONS.includes(action as DesktopArtifactBrowserAction)) {
    throw new Error('Choose a supported Desktop artifact browser action.')
  }
  if (action === 'click' || action === 'focus') {
    const request = parseRequest(
      value,
      ['version', 'action', 'anchor', 'candidateHandle'],
      'browser action',
    )
    return {
      version: request.version as DesktopArtifactBridgeProtocolVersion,
      action,
      anchor: parseAnchor(request.anchor),
      ...(parseOptionalCandidateHandle(request) === undefined
        ? {}
        : { candidateHandle: parseOptionalCandidateHandle(request) }),
    }
  }
  if (action === 'type') {
    const request = parseRequest(
      value,
      ['version', 'action', 'anchor', 'text', 'replace', 'candidateHandle'],
      'browser action',
    )
    if (
      typeof request.text !== 'string'
      || request.text.length > 16_384
      || /\u0000/.test(request.text)
      || typeof request.replace !== 'boolean'
    ) {
      throw new Error('The Desktop artifact browser text input is invalid.')
    }
    return {
      version: request.version as DesktopArtifactBridgeProtocolVersion,
      action,
      anchor: parseAnchor(request.anchor),
      text: request.text,
      replace: request.replace,
      ...(parseOptionalCandidateHandle(request) === undefined
        ? {}
        : { candidateHandle: parseOptionalCandidateHandle(request) }),
    }
  }
  if (action === 'press') {
    const request = parseRequest(
      value,
      ['version', 'action', 'key', 'candidateHandle'],
      'browser action',
    )
    if (!DESKTOP_ARTIFACT_BROWSER_KEYS.includes(request.key as DesktopArtifactBrowserKey)) {
      throw new Error('Choose a supported Desktop artifact browser key.')
    }
    return {
      version: request.version as DesktopArtifactBridgeProtocolVersion,
      action,
      key: request.key as DesktopArtifactBrowserKey,
      ...(parseOptionalCandidateHandle(request) === undefined
        ? {}
        : { candidateHandle: parseOptionalCandidateHandle(request) }),
    }
  }
  const request = parseRequest(
    value,
    ['version', 'action', 'direction', 'amount', 'candidateHandle'],
    'browser action',
  )
  const direction = request.direction
  const amount = request.amount
  if (
    (direction !== 'up' && direction !== 'down'
      && direction !== 'left' && direction !== 'right')
    || (amount !== 'line' && amount !== 'page')
  ) {
    throw new Error('Choose a supported Desktop artifact scroll action.')
  }
  return {
    version: request.version as DesktopArtifactBridgeProtocolVersion,
    action: 'scroll',
    direction,
    amount,
    ...(parseOptionalCandidateHandle(request) === undefined
      ? {}
      : { candidateHandle: parseOptionalCandidateHandle(request) }),
  }
}

export function parseDesktopArtifactBindCandidatePreviewRequest(
  value: unknown,
): DesktopArtifactBindCandidatePreviewRequest {
  const request = parseV4OnlyRequest(
    value,
    ['version', 'candidateHandle'],
    'candidate preview binding',
  )
  return {
    version: request.version as DesktopArtifactBridgeProtocolVersion,
    candidateHandle: parseCandidateHandle(request.candidateHandle),
  }
}

export function parseDesktopArtifactRestoreCanonicalPreviewRequest(
  value: unknown,
): DesktopArtifactRestoreCanonicalPreviewRequest {
  const request = parseV4OnlyRequest(
    value,
    ['version', 'candidateHandle'],
    'canonical preview restore',
  )
  return {
    version: request.version as DesktopArtifactBridgeProtocolVersion,
    candidateHandle: parseCandidateHandle(request.candidateHandle),
  }
}

export function parseDesktopArtifactScreenshotRequest(
  value: unknown,
): DesktopArtifactScreenshotRequest {
  const request = parseRequest(value, ['version', 'candidateHandle'], 'screenshot')
  const candidateHandle = parseOptionalCandidateHandle(request)
  return {
    version: requestVersion(value),
    ...(candidateHandle === undefined ? {} : { candidateHandle }),
  }
}

export function parseDesktopArtifactOfficeFlushRequest(
  value: unknown,
): DesktopArtifactOfficeFlushRequest {
  return parseVersionOnlyRequest(value, 'Office flush')
}

export function parseDesktopArtifactReloadSurfaceRequest(
  value: unknown,
): DesktopArtifactReloadSurfaceRequest {
  const request = parseRequest(value, ['version', 'candidateHandle'], 'surface reload')
  const candidateHandle = parseOptionalCandidateHandle(request)
  return {
    version: requestVersion(value),
    ...(candidateHandle === undefined ? {} : { candidateHandle }),
  }
}
