"""Stable contracts shared by runtime boundaries."""

from opensquilla.contracts.turn_execution import (
    AnswerGenerationResetEvent,
    AssistantMessageReservation,
    CallAttemptLedger,
    CleanupHandle,
    CompletedToolRecord,
    GenerationState,
    PendingToolBuffer,
    ProviderAdmissionError,
    ProviderCallLease,
    RecoveryContext,
    RoleActivationResult,
    StickyExecutionRole,
    SurfaceCapabilities,
    TurnExecutionContext,
    TurnExecutionError,
    TurnIdentity,
    TurnPublicationLedger,
    UsageExecutionLeg,
)

__all__ = [
    "AnswerGenerationResetEvent",
    "AssistantMessageReservation",
    "CallAttemptLedger",
    "CleanupHandle",
    "CompletedToolRecord",
    "GenerationState",
    "PendingToolBuffer",
    "ProviderAdmissionError",
    "ProviderCallLease",
    "RecoveryContext",
    "RoleActivationResult",
    "StickyExecutionRole",
    "SurfaceCapabilities",
    "TurnExecutionContext",
    "TurnExecutionError",
    "TurnIdentity",
    "TurnPublicationLedger",
    "UsageExecutionLeg",
]
